In [4]:
#Previous Assignment Solution(Nine Lives)

import random
lives=9
heart_symbol = '\u2764' #its a unicode for printing heart symbol
words=['guess','pizza','brave','hello','fairy','teeth','roast']
secret_word=random.choice(words)
clue = list('?????')
guess_word = False

In [5]:
def update_clue(guessed_letter,secret_word,clue):
    index = 0
    while index<len(secret_word):
        if guessed_letter == secret_word[index]:
            clue[index] == guessed_letter
        index += 1    

In [6]:
while lives > 0:
    print(clue)
    print("lives left:",heart_symbol*lives)
    guess = input("Guess a letter or whole word")
    if guess == secret_word:
        guess_word = True
        break
    elif guess in secret_word:
        update_clue(guess,secret_word,clue)
    else :
        print("Incorrect guess, you lose a life")
        lives -= 1
if guess_word == True:
    print("You WON the game,Secret_Word was:",secret_word)
else:
    print("You Lose the game, Secret word was:",secret_word)
        

['?', '?', '?', '?', '?']
lives left: ❤❤❤❤❤❤❤❤❤
Guess a letter or whole wordg
Incorrect guess, you lose a life
['?', '?', '?', '?', '?']
lives left: ❤❤❤❤❤❤❤❤
Guess a letter or whole wordp
Incorrect guess, you lose a life
['?', '?', '?', '?', '?']
lives left: ❤❤❤❤❤❤❤
Guess a letter or whole wordb
['?', '?', '?', '?', '?']
lives left: ❤❤❤❤❤❤❤
Guess a letter or whole wordbrave
You WON the game,Secret_Word was: brave


## Numpy package:
- numeric
- computation

In [7]:
import numpy as np

### Differenes b/w numpy array and List:
1. less memory 
2. fast 
3. convenient

In [8]:
#1-dimentional array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(a1.ndim) #gives the dimention of array

2


In [11]:
a1.shape #to find no. of rows and coloumns

(3, 3)

In [13]:
type(a.shape)

tuple

In [14]:
print(a1.shape[0])#rows
print(a1.shape[1])#coloumns

3
3


In [15]:
#create 1 d and 2 d arrays
a=np.array([4,8,9,6])
a

array([4, 8, 9, 6])

In [16]:
b=np.array([[3,5,9],[4,6,8],[2,3,4]])
b

array([[3, 5, 9],
       [4, 6, 8],
       [2, 3, 4]])

In [20]:
#creating arrays by user input i.e dynamically

a3 = np.array([],dtype='int32')

In [21]:
a3 = np.append(a3,int(input()))
a3

12


array([12])

In [22]:
a3 = np.append(a3,[13,58,36,46])
a3

array([12, 13, 58, 36, 46])

In [24]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Slicing:

In [25]:
print(a3[3])

36


In [26]:
print(a1[1,1])

5


In [28]:
print(a1[2:,:]) #from second row all coloumns 

[[7 8 9]]


In [29]:
print(a1[2:,0:2]) #last digit is for coloumn i.e end-1=1

[[7 8]]


In [33]:
print(a1[0,0:2])

[1 2]


## Iterate through array:

In [34]:
for row in a1: # the value will be row of array
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [35]:
list1 = [[1,2],[3,4]]
for i in list1:
    print(i)

[1, 2]
[3, 4]


In [36]:
for ele in a1.flat: # flat attribute flattens all elements of array irrespective of shape
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 

In [38]:
np.array(a1.flat)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Indexing with boolean array

In [39]:
ar = np.arange(1,21)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
ar = np.arange(1,21).reshape(5,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [42]:
result = (ar % 2 == 0)

In [43]:
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [44]:
ar[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Appending Arrays

In [47]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))#vertical stack

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [48]:
print(np.hstack((arr1,arr2)))#horizontal stack

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


### Attributes of numpy array:
1. size
2. itemsize
3. dtype
4. ndim
5. shape

In [50]:
arr=np.arange(1,11).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

10
8
int64
2
(2, 5)


### Functions:
1. zeros()
2. ones()
3. full()
4. eye() #creates diagonal matrix
5. linspace()
6. arange()
7. reshape()
8. ravel()

In [52]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
z=np.zeros((2,3),dtype="int32")
z

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [55]:
one=np.ones((2,3),dtype="int32")
one

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [57]:
f=np.full((2,2),"PR")
f

array([['PR', 'PR'],
       ['PR', 'PR']], dtype='<U2')

In [58]:
e = np.eye(3,dtype="int32")
e

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [60]:
#linspace()--> linear spacing elements
l = np.linspace(1,10,5) #starting and ending ranges will get devided into equal parts here it is 5 equal parts
l

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [61]:
#ravel -->flattens your array elements
print(np.array(a.flat))
print(a.ravel())

[4 8 9 6]
[4 8 9 6]


### Functions which perform basic operations:
1. min()
2. max()
3. sum()
4. axis()
5. sqrt()
6. mean()
7. median()
8. std()
- we dont have mode function in numpy package


In [63]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [67]:
print(ar.min())
print(ar.max())
print(ar.sum())#gives sum of all the elements of an array
print(ar.sum(axis=1))#sum of row elements 

1
20
210
[10 26 42 58 74]


In [71]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162],
       [3.60555128, 3.74165739, 3.87298335, 4.        ],
       [4.12310563, 4.24264069, 4.35889894, 4.47213595]])

In [72]:
np.mean(ar)

10.5

In [73]:
np.median(ar)

10.5

In [74]:
np.std(ar) # its for standard deviation

5.766281297335398

### Mathematical operations on array: +,-,*,/,%


In [76]:
a1 = np.array([[3,4,5],[8,9,2],[4,6,3]])
a1

array([[3, 4, 5],
       [8, 9, 2],
       [4, 6, 3]])

In [77]:
a2 = np.array([[8,9,2],[4,6,3],[3,4,5]])
a2

array([[8, 9, 2],
       [4, 6, 3],
       [3, 4, 5]])

In [78]:
a1+a2

array([[11, 13,  7],
       [12, 15,  5],
       [ 7, 10,  8]])

In [79]:
a1-a2

array([[-5, -5,  3],
       [ 4,  3, -1],
       [ 1,  2, -2]])

In [80]:
a1*a2

array([[24, 36, 10],
       [32, 54,  6],
       [12, 24, 15]])

In [81]:
a1/a2

array([[0.375     , 0.44444444, 2.5       ],
       [2.        , 1.5       , 0.66666667],
       [1.33333333, 1.5       , 0.6       ]])

In [82]:
a1%a2

array([[3, 4, 1],
       [0, 3, 2],
       [1, 2, 3]])

### dot()-->Matrix multiplication
### arr1 = m X n
### arr2 = n X o

In [83]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [85]:
arr1.T # capital T is used for transpose of an array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Applying user -defined function:

In [86]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [87]:
result = [x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [91]:
f = np.vectorize(lambda x : x/(x+1))
f(ar)

array([[0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     , 0.88888889],
       [0.9       , 0.90909091, 0.91666667, 0.92307692],
       [0.92857143, 0.93333333, 0.9375    , 0.94117647],
       [0.94444444, 0.94736842, 0.95      , 0.95238095]])